apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: insta-bridge
  name: insta-bridge
  namespace: matrix
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: insta-bridge
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: insta-bridge
      name: matrix
    spec:
      containers:
        - image: dock.mau.dev/mautrix/meta:v25.12
          imagePullPolicy: Always
          name: insta-bridge
          env:
            - name: PGSSLMODE
              value: disable
            - name: MAUTRIX_database.uri
              valueFrom:
                secretKeyRef:
                  name: pg-insta-bridge-app
                  key: uri
            - name: MAUTRIX_double_puppet.secrets.ak-online.be
              valueFrom:
                secretKeyRef:
                  name: synapse
                  key: puppettoken
          envFrom:
            - secretRef:
                name: insta-bridge
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /data/config.yaml
              name: cm
              subPath: config.yaml
            - mountPath: /data/registration.yaml
              name: as
              subPath: registration.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      volumes:
        - name: data
          emptyDir:
        - name: cm
          configMap:
            name: insta-bridge
            defaultMode: 420
        - name: as
          secret:
            secretName: as-insta-bridge
