resources:
  - cluster-pg-insta-bridge.yaml
  - db-scheduledbackup-insta-bridge.yaml
  - deployment.yaml
  - svc.yaml

configMapGenerator:
  - name: insta-bridge
    files:
      - config/config.yaml
    options:
      disableNameSuffixHash: true
