apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: disco-bridge
  name: disco-bridge
  namespace: matrix
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: disco-bridge
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: disco-bridge
      name: disco-bridge
    spec:
      initContainers:
        - image: dock.mau.dev/mautrix/discord:latest
          name: copy-config
          volumeMounts:
          - mountPath: /copy-and-merge-config.sh
            name: copy-and-merge-config-script
            subPath: copy-and-merge-config.sh
          - mountPath: /data
            name: disco-pv
            subPath: disco
          - mountPath: /cm/config.yaml
            name: disco-cm
            subPath: config.yaml
          - mountPath: /cm/secrets.yaml
            name: secrets
            subPath: secrets.yaml
          - mountPath: /cm/registration.yaml
            name: as
            subPath: registration.yaml
          command:
            - /copy-and-merge-config.sh
      containers:
      - image: dock.mau.dev/mautrix/discord:latest
        imagePullPolicy: Always
        name: disco-bridge
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: disco-pv
          subPath: disco
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      volumes:
      - name: disco-pv
        persistentVolumeClaim:
          claimName: disco-storage
      - name: disco-cm
        configMap:
          name: disco-bridge
          defaultMode: 420
      - name: as
        secret:
          secretName: as-disco-bridge
          defaultMode: 420
      - name: secrets
        secret:
          secretName: disco-bridge
      - name: copy-and-merge-config-script
        configMap:
          name: copy-and-merge-config-script
          defaultMode: 0o530
