resources:
  - cluster-pg-disco-bridge.yaml
  - db-scheduledbackup-disco-bridge.yaml
  - deployment.yaml
  - svc.yaml

configMapGenerator:
  - name: disco-bridge
    files:
      - config/config.yaml
    options:
      disableNameSuffixHash: true
