resources:
  - cluster-pg-gc-bridge.yaml
  - db-scheduledbackup-gc-bridge.yaml
  - deployment.yaml
  - svc.yaml

configMapGenerator:
  - name: gc-bridge
    files:
      - config/config.yaml
    options:
      disableNameSuffixHash: true
