resources:
  - cluster-pg-wa-bridge.yaml
  - db-scheduledbackup-wa-bridge.yaml
  - deployment.yaml
  - svc.yaml

configMapGenerator:
  - name: wa-bridge
    files:
      - config/config.yaml
    options:
      disableNameSuffixHash: true
