apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 550m
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: matrix
  namespace: matrix
spec:
  ingressClassName: nginx
  rules:
    - host: matrix.cloud.ak-online.be
      http:
        paths:
          - path: /
            backend:
              service:
                name: synapse
                port:
                  number: 80
            pathType: ImplementationSpecific
          - path: /_matrix/client/(.*)/(login|logout|refresh)
            backend:
              service:
                name: mas
                port:
                  number: 80
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - matrix.cloud.ak-online.be
      secretName: matrix-prod-ingress
