resources:
  - 000_ns.yaml
  - 001_pvc_postgres.yaml
  - 004_postgres_deployment.yaml
  - 005_postgres_svc.yaml
  - matrix-config
  - 014_pvc.yaml
  - 015_deployment.yaml
  - 017_svc_synapse.yaml
  - 018_ingress.yaml
  - secrets.enc.yaml
  - gc-bridge
  - disco-bridge
  - insta-bridge
  - wa-bridge

configMapGenerator:
  - name: copy-and-merge-config-script
    files:
      - copy-and-merge-config.sh
    options:
      disableNameSuffixHash: true

namespace: matrix
