resources:
  - namespace-matrix.yaml
  - secrets.enc.yaml

  - pvc-postgres.yaml
  - deployment-postgres.yaml
  - service-postgres-13.yaml

  - pvc-synapse.yaml
  - matrix-config
  - deployment-matrix.yaml
  - service-synapse.yaml
  - ingress-matrix.yaml

  - gc-bridge
  - disco-bridge
  - insta-bridge
  - wa-bridge

configMapGenerator:
  - name: copy-and-merge-config-script
    files:
      - copy-and-merge-config.sh
    options:
      disableNameSuffixHash: true

namespace: matrix
