resources:
  - namespace-matrix.yaml
  - secrets.enc.yaml

  - cluster-pg-synapse.yaml
  - cluster-pg-disco-bridge.yaml
  - cluster-pg-gc-bridge.yaml
  - cluster-pg-insta-bridge.yaml
  - cluster-pg-wa-bridge.yaml

  - db-scheduledbackup-synapse.yaml
  - db-scheduledbackup-disco-bridge.yaml
  - db-scheduledbackup-gc-bridge.yaml
  - db-scheduledbackup-insta-bridge.yaml
  - db-scheduledbackup-wa-bridge.yaml

  - pvc-synapse.yaml
  - matrix-config
  - deployment-matrix.yaml
  - service-synapse.yaml
  - ingress-matrix.yaml

  - gc-bridge
  - disco-bridge
  - insta-bridge
  - wa-bridge

configMapGenerator:
  - name: copy-and-merge-config-script
    files:
      - copy-and-merge-config.sh
    options:
      disableNameSuffixHash: true

namespace: matrix
