resources:
  - namespace-matrix.yaml
  - secrets.enc.yaml

  - deployment-mx.yaml
  - service-mx.yaml

  - db-backup-store.yaml

  - cluster-pg-synapse.yaml
  - db-scheduledbackup-synapse.yaml

  - pvc-synapse.yaml
  - matrix-config
  - deployment-matrix.yaml
  - service-synapse.yaml
  - ingress-matrix.yaml

  - gc-bridge
  - disco-bridge
  - insta-bridge
  - wa-bridge

configMapGenerator:
  - name: copy-and-merge-config-script
    files:
      - copy-and-merge-config.sh
    options:
      disableNameSuffixHash: true

namespace: matrix
