apiVersion: v1
kind: Service
metadata:
  name: auth-config
  namespace: bolcz
spec:
  selector:
    app: auth-config
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
