apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: gmsg-bridge
  name: gmsg-bridge
  namespace: matrix
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: gmsg-bridge
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: gmsg-bridge
      name: gmsg-bridge
    spec:
      initContainers:
        - image: dock.mau.dev/mautrix/gmessages:v26.01
          name: copy-config
          volumeMounts:
            - mountPath: /copy-and-merge-config.sh
              name: copy-and-merge-config-script
              subPath: copy-and-merge-config.sh
            - mountPath: /data
              name: data
            - mountPath: /cm/config.yaml
              name: gmsg-cm
              subPath: config.yaml
            - mountPath: /cm/registration.yaml
              name: as
              subPath: registration.yaml
          command:
            - /copy-and-merge-config.sh
      containers:
        - image: dock.mau.dev/mautrix/gmessages:v26.01
          imagePullPolicy: Always
          name: gmsg-bridge
          env:
            - name: PGSSLMODE
              value: disable
            - name: MAUTRIX_database.uri
              valueFrom:
                secretKeyRef:
                  name: pg-gmsg-bridge-app
                  key: uri
            - name: MAUTRIX_double_puppet.secrets.ak-online.be
              valueFrom:
                secretKeyRef:
                  name: synapse
                  key: puppettoken
          envFrom:
            - secretRef:
                name: gmsg-bridge
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      volumes:
        - name: data
          emptyDir:
        - name: gmsg-cm
          configMap:
            name: gmsg-bridge
        - name: as
          secret:
            secretName: as-gmsg-bridge
        - name: copy-and-merge-config-script
          configMap:
            name: copy-and-merge-config-script
            defaultMode: 0o530
